# fly.toml file generated for botm-fly-log-shipper on 2023-07-08T13:53:03+02:00

app = "botm-fly-log-shipper"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ams"
processes = []

[build]
  image = "ghcr.io/superfly/fly-log-shipper:latest"

[[services]]
  http_checks = []
  internal_port = 8686
